In [2]:
import numpy as np

## Main Shimbell index calculation

## Setting input values

In [3]:


c = np.array([ [0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0],
      [1,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0],
      [1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
      [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
      [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
      [0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
      [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],
      [0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0],
      [0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0],
      [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
      [0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0],
      [0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,0],
      [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
      [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1],
      [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
      [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0], ])

print(c)
print(c.shape)

[[0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]
(16, 16)


### Shimbell matrix verification function

In [5]:
def fun(mat):
  non_diag = np.ones(shape=mat.shape, dtype=bool) ^ np.identity(len(mat)).astype(bool) # https://stackoverflow.com/a/35746922
  bool_mat = np.array(mat, dtype=bool)
  return np.array_equal(bool_mat,non_diag)

## Shimbell matrix calculation function

In [6]:
def dyad_calculation(c):
  n = 1
  k = np.identity(len(c))
  d = np.zeros([len(c),len(c)])
  while not fun(d):
    k = np.dot(c,k)
    print("The matrix multiplication is \n", k)
    for i in range(0,len(c)):
      for j in range(0,len(c)):
        if k[i][j]!=0 and d[i][j]==0:
          d[i][j] = n
      d[i][i] = 0
      
    n = n + 1
    print("The D value is \n",d)
    print(fun(d))
  print("The dyad value is \n",d)
  print("The shortest paths from each vertices to other vertices", np.sum(d,axis=0))


In [7]:
dyad_calculation(c)

The matrix multiplication is 
 [[0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
The D value is 
 [[0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0